import { join, relative, sep } from "node:path"
import { stringify as stringifyYaml } from "yaml"
import { loadProjectConfig, loadTaxonomy } from "./config.js"
import {
  emptyDirectory,
  listFilesRecursive,
  readJsonLines,
  readUtf8,
  sha256,
  slugify,
  writeJson,
  writeUtf8,
} from "./files.js"
import {
  CanonicalClaimSchema,
  CanonicalEntitySchema,
  CanonicalPassageSchema,
  CanonicalRelationshipSchema,
  SegmentExtractionSchema,
  SegmentSchema,
  type CanonicalEntity,
  type Provenance,
} from "./model.js"

export async function renderObsidian(root: string): Promise<{ files: number; hash: string }> {
  const config = await loadProjectConfig(root)
  const taxonomy = await loadTaxonomy(root)
  const dataRoot = join(root, config.output.data)
  const outputRoot = join(root, config.output.obsidian)
  const [segments, extractions, entities, claims, relationships, passages] = await Promise.all([
    readJsonLines(join(dataRoot, "segments.jsonl"), SegmentSchema),
    readJsonLines(join(dataRoot, "extractions.jsonl"), SegmentExtractionSchema),
    readJsonLines(join(dataRoot, "entities.jsonl"), CanonicalEntitySchema),
    readJsonLines(join(dataRoot, "claims.jsonl"), CanonicalClaimSchema),
    readJsonLines(join(dataRoot, "relationships.jsonl"), CanonicalRelationshipSchema),
    readJsonLines(join(dataRoot, "passages.jsonl"), CanonicalPassageSchema),
  ])
  await emptyDirectory(outputRoot)

  const categoryById = new Map(taxonomy.categories.map((category) => [category.id, category]))
  const entityById = new Map(entities.map((entity) => [entity.id, entity]))
  const entityPaths = allocateEntityPaths(entities, categoryById)
  const chapterPaths = new Map(
    segments.map((segment) => [
      segment.id,
      `Chapters/${String(segment.ordinal).padStart(4, "0")}-${slugify(segment.title)}`,
    ]),
  )
  const chapterTitles = new Map(segments.map((segment) => [segment.id, inlineText(segment.title)]))
  const chapterLabels = new Map(
    segments.map((segment) => [
      segment.id,
      chapterLabel(segment.ordinal, chapterTitles.get(segment.id) ?? segment.title),
    ]),
  )
  const passagePaths = new Map(
    passages.map((passage) => [
      passage.id,
      `Passages/${slugify(passage.title)}-${passage.id.slice(-8)}`,
    ]),
  )

  await writeUtf8(
    join(outputRoot, "index.md"),
    page(
      { title: config.title, type: "home", tags: ["plot-tools/home"] },
      [
        `# ${config.title}`,
        "",
        "A source-grounded narrative graph generated by [dont-lose-the-plot](https://github.com/bjb2/dont-lose-the-plot).",
        "",
        "## Browse",
        "",
        "- [[Chapters/index|Reading order]]",
        "- [[Entities|Entity index]]",
        "- [[Passages/index|Passage index]]",
        "- [[Taxonomy|Taxonomy]]",
      ].join("\n"),
    ),
  )

  await writeUtf8(
    join(outputRoot, "Chapters", "index.md"),
    page(
      { title: "Reading order", type: "index" },
      [
        "# Reading order",
        "",
        ...segments.map((segment) => {
          const title = chapterTitles.get(segment.id) ?? segment.title
          return `- [[${chapterPaths.get(segment.id)}|${segment.ordinal}. ${title}]]`
        }),
      ].join("\n"),
    ),
  )

  for (const segment of segments) {
    const title = chapterTitles.get(segment.id) ?? segment.title
    const extraction = extractions.find((candidate) => candidate.segmentId === segment.id)
    if (!extraction) continue
    const mentioned = entities.filter((entity) =>
      entity.mentions.some((mention) => mention.segmentId === segment.id),
    )
    const relatedPassages = passages.filter(
      (passage) => passage.provenance.segmentId === segment.id,
    )
    const body = [
      `# ${title}`,
      "",
      extraction.summary,
      "",
      "## Plot beats",
      "",
      ...listOrEmpty(extraction.plotBeats),
      "",
      "## Entities",
      "",
      ...listOrEmpty(
        mentioned.map(
          (entity) =>
            `[[${entityPaths.get(entity.id)}|${entity.canonicalName}]] — ${entity.summary}`,
        ),
      ),
      "",
      "## Themes",
      "",
      ...listOrEmpty(extraction.themes),
      "",
      "## Passages",
      "",
      ...listOrEmpty(
        relatedPassages.map((passage) => `[[${passagePaths.get(passage.id)}|${passage.title}]]`),
      ),
    ].join("\n")
    await writeUtf8(
      join(outputRoot, `${chapterPaths.get(segment.id)}.md`),
      page(
        {
          title,
          type: "chapter",
          ordinal: segment.ordinal,
          source: segment.sourceId,
          locator: segment.locator,
          tags: ["plot-tools/chapter"],
        },
        body,
      ),
    )
  }

  for (const entity of entities) {
    const entityClaims = claims.filter((claim) => claim.entityId === entity.id)
    const outbound = relationships.filter((relationship) => relationship.subjectId === entity.id)
    const inbound = relationships.filter((relationship) => relationship.objectId === entity.id)
    const relatedPassages = passages.filter(
      (passage) => passage.speakerId === entity.id || passage.entityIds.includes(entity.id),
    )
    const body = [
      `# ${entity.canonicalName}`,
      "",
      entity.summary,
      "",
      "## Facts",
      "",
      ...listOrEmpty(
        entityClaims.map(
          (claim) =>
            `${claim.text} ${citation(
              claim.provenance,
              chapterPaths,
              chapterLabels,
              config.publication.includeExcerpts,
              config.publication.maxExcerptCharacters,
            )}`,
        ),
      ),
      "",
      "## Relationships",
      "",
      ...listOrEmpty([
        ...outbound.map((relationship) =>
          renderRelationship(
            relationship.predicate,
            relationship.objectId,
            relationship.literalObject,
            entityById,
            entityPaths,
          ),
        ),
        ...inbound.map((relationship) => {
          const subject = entityById.get(relationship.subjectId)
          return subject
            ? `[[${entityPaths.get(subject.id)}|${subject.canonicalName}]] — ${relationship.predicate}`
            : relationship.subjectId
        }),
      ]),
      "",
      "## Appearances",
      "",
      ...entity.mentions.map(
        (mention) =>
          `- [[${chapterPaths.get(mention.segmentId)}|${chapterLabels.get(mention.segmentId)}]]${renderExcerpt(mention, config.publication.includeExcerpts, config.publication.maxExcerptCharacters)}`,
      ),
      "",
      "## Passages",
      "",
      ...listOrEmpty(
        relatedPassages.map((passage) => `[[${passagePaths.get(passage.id)}|${passage.title}]]`),
      ),
    ].join("\n")
    await writeUtf8(
      join(outputRoot, `${entityPaths.get(entity.id)}.md`),
      page(
        {
          title: entity.canonicalName,
          aliases: entity.aliases,
          type: entity.category,
          salience: entity.salience,
          certainty: entity.certainty,
          firstSeen: entity.firstSeen.segmentOrdinal,
          tags: ["plot-tools/entity", `plot-tools/${entity.category}`],
          ...entity.attributes,
        },
        body,
      ),
    )
  }

  await writeUtf8(
    join(outputRoot, "Entities.md"),
    page(
      { title: "Entity index", type: "index" },
      [
        "# Entity index",
        "",
        ...taxonomy.categories.flatMap((category) => {
          const categoryEntities = entities.filter((entity) => entity.category === category.id)
          return categoryEntities.length === 0
            ? []
            : [
                `## ${category.labels.plural}`,
                "",
                ...categoryEntities.map(
                  (entity) => `- [[${entityPaths.get(entity.id)}|${entity.canonicalName}]]`,
                ),
                "",
              ]
        }),
      ].join("\n"),
    ),
  )

  await writeUtf8(
    join(outputRoot, "Passages", "index.md"),
    page(
      { title: "Passage index", type: "index" },
      [
        "# Passage index",
        "",
        ...passages.map((passage) => `- [[${passagePaths.get(passage.id)}|${passage.title}]]`),
      ].join("\n"),
    ),
  )

  for (const passage of passages) {
    const linkedEntities = passage.entityIds
      .map((id) => entityById.get(id))
      .filter((entity): entity is CanonicalEntity => entity !== undefined)
    const body = [
      `# ${passage.title}`,
      "",
      `> ${truncate(passage.text, config.publication.maxExcerptCharacters)}`,
      "",
      passage.context,
      "",
      `**Why it matters:** ${passage.significance}`,
      "",
      `**Source:** [[${chapterPaths.get(passage.provenance.segmentId)}|${chapterLabels.get(passage.provenance.segmentId)}]]`,
      "",
      "## Entities",
      "",
      ...listOrEmpty(
        linkedEntities.map((entity) => `[[${entityPaths.get(entity.id)}|${entity.canonicalName}]]`),
      ),
    ].join("\n")
    await writeUtf8(
      join(outputRoot, `${passagePaths.get(passage.id)}.md`),
      page(
        {
          title: passage.title,
          type: "passage",
          kind: passage.kind,
          certainty: passage.certainty,
          complete: passage.complete,
          tags: ["plot-tools/passage", `plot-tools/passage/${passage.kind}`],
        },
        body,
      ),
    )
  }

  await writeUtf8(
    join(outputRoot, "Taxonomy.md"),
    page(
      { title: "Taxonomy", type: "index" },
      [
        "# Taxonomy",
        "",
        ...taxonomy.categories.flatMap((category) => [
          `## ${category.labels.plural}`,
          "",
          category.definition,
          "",
        ]),
      ].join("\n"),
    ),
  )
  await writeUtf8(join(outputRoot, ".obsidian", "app.json"), "{}\n")
  await writeUtf8(join(outputRoot, ".obsidian", "graph.json"), "{}\n")

  const files = await listFilesRecursive(outputRoot)
  const digestInput: string[] = []
  for (const file of files) {
    digestInput.push(relative(outputRoot, file).split(sep).join("/"), await readUtf8(file))
  }
  const hash = sha256(digestInput.join("\u0000"))
  await writeJson(join(root, ".plot-tools", "render-manifest.json"), {
    schemaVersion: 1,
    files: files.length,
    hash,
  })
  return { files: files.length, hash }
}

function allocateEntityPaths(
  entities: CanonicalEntity[],
  categoryById: Map<string, { folder: string }>,
): Map<string, string> {
  const output = new Map<string, string>()
  const used = new Set<string>()
  for (const entity of entities) {
    const folder = categoryById.get(entity.category)?.folder ?? "Other"
    const base = `${folder}/${slugify(entity.canonicalName)}`
    const path = used.has(base) ? `${base}-${entity.id.slice(-8)}` : base
    output.set(entity.id, path)
    used.add(path)
  }
  return output
}

function renderRelationship(
  predicate: string,
  objectId: string | null,
  literalObject: string | null,
  entityById: Map<string, CanonicalEntity>,
  entityPaths: Map<string, string>,
): string {
  if (objectId) {
    const object = entityById.get(objectId)
    if (object) return `${predicate} → [[${entityPaths.get(object.id)}|${object.canonicalName}]]`
  }
  return `${predicate} → ${literalObject ?? "unresolved"}`
}
function inlineText(value: string): string {
  return value.replace(/\s+/g, " ").trim()
}

function chapterLabel(ordinal: number, title: string): string {
  const cleanTitle = title.replace(/^chapter\s+(?:[ivxlcdm]+|\d+)[.:\s–—-]*/i, "").trim()
  return cleanTitle ? `Chapter ${ordinal}: ${cleanTitle}` : `Chapter ${ordinal}`
}

function citation(
  provenance: Provenance,
  chapterPaths: Map<string, string>,
  chapterLabels: Map<string, string>,
  includeExcerpt: boolean,
  maxCharacters: number,
): string {
  return `([[${chapterPaths.get(provenance.segmentId)}|${chapterLabels.get(provenance.segmentId)}]])${renderExcerpt(provenance, includeExcerpt, maxCharacters)}`
}

function renderExcerpt(provenance: Provenance, include: boolean, maxCharacters: number): string {
  return include && provenance.excerpt ? ` — “${truncate(provenance.excerpt, maxCharacters)}”` : ""
}

function truncate(value: string, maxCharacters: number): string {
  if (value.length <= maxCharacters) return value
  return `${value.slice(0, Math.max(0, maxCharacters - 1)).trimEnd()}…`
}

function listOrEmpty(values: string[]): string[] {
  return values.length === 0 ? ["- None recorded."] : values.map((value) => `- ${value}`)
}

function page(frontmatter: Record<string, unknown>, body: string): string {
  return `---\n${stringifyYaml(frontmatter).trimEnd()}\n---\n\n${body.trim()}\n`
}
